import type { Metadata } from "next";
import { Inter } from "next/font/google";
// styles
import "@/public/styles/global.css";
import Header from "@/components/Header";
import { CustomFlowbiteTheme, Flowbite } from "flowbite-react";

import { useEffect } from "react";
import { initFlowbite } from "flowbite";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Proj - E - ticket",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const customTheme: CustomFlowbiteTheme = {
    textInput: {
      field: {
        input: {
          colors: {
            header_search_input: "bg-gray-900 text-white rounded-md",
          },
          sizes: {
            header_search_input: "p-2 my-4",
          },
        },
      },
    },
    dropdown: {
      floating: {
        target: "w-full",
        style: {
          dark: "bg-transparent text-white dark:bg-transparent",
          light: "bg-transparent text-gray-900",
          auto: "bg-transparent text-gray-900 dark:bg-transparent dark:text-white ",
        },
      },
    },
    drawer: {
      items: {
        base: "w-full",
      },
      root: {
        position: {
          right: {
            on: "right-0 top-[74px] h-screen w-[650px] ",
          },
        },
      },
      header: {
        collapsed: {
          on: "hidden",
          off: "block",
        },
      },
    },
    tabs: {
      tabitemcontainer: {
        styles: {
          fullWidth: "",
        },
      },
    },
    accordion: {
      root: {
        base: "divide-y divide-gray-200 border-gray-100 dark:divide-gray-100 dark:border-gray-100",
        flush: {
          off: "rounded-lg border-gray-100 dark:border-gray-100",
          on: "border-b",
        },
      },
      content: {
        base: "p-5 first:rounded-t-lg last:rounded-b-lg dark:bg-[#EEEEEE]",
      },
      title: {
        arrow: {
          base: "h-6 w-6 shrink-0",
          open: {
            off: "",
            on: "rotate-180",
          },
        },
        base: "flex w-full items-center justify-between p-5 text-left font-medium text-gray-500 first:rounded-t-lg last:rounded-b-lg dark:text-gray-400",
        flush: {
          off: "hover:bg-transparent focus:ring-0 focus:ring-gray-0 dark:hover:bg-transparent dark:focus:ring-transparent",
          on: "bg-transparent dark:bg-transparent",
        },
        heading: "flex justify-start",
        open: {
          off: "",
          on: "bg-[#eeeeee] text-black dark:bg-black dark:text-black",
        },
      },
    },
    button: {
      color: {
        info: "",
      },
    },
    popover: {
      base: "absolute z-20 inline-block w-max max-w-[100vw] bg-white outline-none border border-gray-200 rounded-lg shadow-sm dark:border-gray-600 dark:bg-gray-800",
      content: "z-10 overflow-hidden rounded-[7px]",
      arrow: {
        base: "absolute h-2 w-2 z-0 rotate-45 mix-blend-lighten bg-white border border-gray-200 dark:border-gray-600 dark:bg-gray-800 dark:mix-blend-color",
        placement: "-4px",
      },
    },
  };

  return (
    <Flowbite theme={{ theme: customTheme }}>
      <html lang="en">
        <body className={inter.className}>
          <Header />

          {children}
        </body>
      </html>
    </Flowbite>
  );
}
